sudo: required
language: javascript

services:
  - docker

before_install:
  - docker build -t john7ric/docker-react -f Dockerfile.dev .

script:
  - docker run -e CT=true john7ric/docker-react npm run test -- --coverage
