sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t john7ric/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true john7ric/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-aws-eb-react"
  environment: "DockerAwsEbReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-438115268593"
  bucket_path: "docker-aws-eb-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  